"use client";

import { useState } from "react";
import type { AppIdentity } from "@aso/shared";
import type { AuditResult } from "@/lib/api";

/**
 * Export affordances for the finished audit: save a polished PDF (via the
 * browser's print pipeline + a dedicated print stylesheet) and copy a plain
 * -text summary reviewers can paste anywhere. No heavy client deps.
 */
export function ExportBar({
  identity,
  result,
}: {
  identity: AppIdentity;
  result: AuditResult;
}) {
  const [copied, setCopied] = useState(false);

  const copySummary = async () => {
    const text = buildSummary(identity, result);
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      /* clipboard blocked — ignore */
    }
  };

  return (
    <div className="bar" data-noprint>
      <button className="act" onClick={() => window.print()}>
        <Icon name="pdf" /> Save PDF
      </button>
      <button className={`act ${copied ? "done" : ""}`} onClick={copySummary}>
        <Icon name={copied ? "check" : "copy"} /> {copied ? "Copied" : "Copy summary"}
      </button>

      <style jsx>{`
        .bar { display: flex; gap: 0.5rem; }
        .act {
          display: inline-flex;
          align-items: center;
          gap: 0.45rem;
          background: var(--surface);
          border: 1px solid var(--line-2);
          color: var(--ink-2);
          border-radius: var(--r-sm);
          padding: 0.5rem 0.85rem;
          font-size: 0.85rem;
          font-weight: 500;
          transition: border-color 0.14s, color 0.14s, transform 0.14s var(--ease),
            background 0.14s;
        }
        .act:hover {
          border-color: var(--accent);
          color: var(--accent);
          transform: translateY(-1px);
        }
        .act:active { transform: translateY(0); }
        .act.done {
          border-color: var(--good);
          color: var(--good);
          background: var(--good-wash);
        }
        @media (max-width: 700px) {
          .bar { width: 100%; }
          .act { flex: 1; justify-content: center; padding: 0.65rem 0.85rem; }
        }
      `}</style>
    </div>
  );
}

function Icon({ name }: { name: "pdf" | "copy" | "check" }) {
  const p =
    name === "pdf"
      ? "M4 2h8l4 4v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2Zm8 0v4h4"
      : name === "check"
        ? "M4 11l5 5L20 5"
        : "M8 4h9a1 1 0 0 1 1 1v11M6 8h9a1 1 0 0 1 1 1v9a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1Z";
  return (
    <svg width="15" height="15" viewBox="0 0 22 22" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
      <path d={p} />
    </svg>
  );
}

function buildSummary(identity: AppIdentity, result: AuditResult): string {
  const { report } = result;
  const lines: string[] = [];
  lines.push(`ASO AUDIT — ${identity.name} (${identity.developer})`);
  lines.push(`Overall: ${report.scoreCard.overall}/100 · Grade ${report.scoreCard.grade}`);
  lines.push("");
  lines.push(report.headline);
  lines.push("");
  lines.push("SCORES");
  for (const d of report.scoreCard.dimensions) {
    lines.push(`  ${d.label.padEnd(20)} ${d.score.toFixed(1)}/10  (${d.weight.toFixed(0)}%)`);
  }
  lines.push("");
  const tiers = [
    ["QUICK WINS", "quick-win"],
    ["HIGH IMPACT", "high-impact"],
    ["STRATEGIC", "strategic"],
  ] as const;
  for (const [label, tier] of tiers) {
    const items = report.recommendations.filter((r) => r.tier === tier);
    if (!items.length) continue;
    lines.push(label);
    for (const r of items) {
      lines.push(`  • ${r.title}`);
      if (r.before && r.after) {
        lines.push(`      from: ${r.before}`);
        lines.push(`      to:   ${r.after}`);
      }
    }
    lines.push("");
  }
  lines.push(`— Generated by ASO Audit · ${identity.storeUrl}`);
  return lines.join("\n");
}
